name: Deploy to aliyun ECS Server

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Remove python
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: "script/py_deploy.sh"
#
#      - name: Deploy to Server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SERVER_ADDRESS }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          source: ${{ github.workspace }}/dist
#          target: /usr/share/nginx/html/
#          rm: true
#          strip_components: 4